#!/bin/sh

perl -e 'while(1){ my $u = `uptime`; chomp $u; $u =~ s/^.*days [\d:]+,//; print localtime() . "$u  processes: " . `ps -e | wc -l`; sleep 5; }' | /usr/bin/cronolog /var/log/stats/uptime-logs/%Y/%m/%d.log
